name: Devops Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with Flake8
        run: flake8 sentiment_analysis/

      - name: Run Tests with Pytest
        run: pytest sentiment_analysis/

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flickr-producer:latest -f Dockerfiles/Dockerfile.producer .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flickr-processor:latest -f Dockerfiles/Dockerfile.processor .
          docker push ${{ secrets.DOCKER_USERNAME }}/flickr-producer:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flickr-processor:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment/flickr-producer
          kubectl rollout restart deployment/flickr-processor
